#!/bin/bash

# Setup Generated Games Directory with OpenSWE Configuration
# This script creates the generated-games directory and adds necessary prompts/instructions

echo "🎮 Setting up generated-games directory for OpenSWE..."

# Navigate to workspace root
WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../.." && pwd)"
echo "📁 Workspace root: $WORKSPACE_ROOT"

# Create generated-games directory structure
GENERATED_GAMES_DIR="$WORKSPACE_ROOT/generated-games"
echo "📁 Creating generated-games directory: $GENERATED_GAMES_DIR"

mkdir -p "$GENERATED_GAMES_DIR"/{.openswe,templates,examples}

# Copy prompts and instructions to generated-games
echo "📝 Adding OpenSWE instructions to generated-games..."

# Copy the main game generation prompt
cp "$WORKSPACE_ROOT/game-builder/src/ai/generate/prompts/chaincraft-game-generation.md" \
   "$GENERATED_GAMES_DIR/.openswe/"

# Create a project-specific README for OpenSWE
cat > "$GENERATED_GAMES_DIR/.openswe/README.md" << 'EOF'
# OpenSWE Configuration for ChainCraft Game Generation

This directory contains instructions and configuration for OpenSWE when generating games.

## Files

- `chaincraft-game-generation.md` - Main prompt for game generation
- `project-context.md` - Project-specific context and constraints
- `README.md` - This file

## Usage

When OpenSWE operates on this directory, it will:
1. Read instructions from `.openswe/` 
2. Reference framework code from `../text-game-engine/`
3. Study examples from `../gamedef/`
4. Generate games in subdirectories

## Generated Game Structure

Each game will be created in its own subdirectory:
```
generated-games/
├── .openswe/           # Instructions (this directory)
├── game-name-1/        # Generated game
├── game-name-2/        # Another generated game
└── ...
```
EOF

# Create project context file
cat > "$GENERATED_GAMES_DIR/.openswe/project-context.md" << 'EOF'
# ChainCraft Project Context

## Project Structure

You are working in a ChainCraft game generation workspace with the following structure:

```
../
├── text-game-engine/   # ECS framework - study this for patterns
├── gamedef/           # Example game definitions
├── game-builder/      # Build system (reference only)
└── generated-games/   # Your working directory (here)
```

## Key References

### Framework Documentation
- `../text-game-engine/docs/` - Core concepts and API documentation
- `../text-game-engine/modules/rps/` - Complete working example

### Example Games
- `../gamedef/` - Game definition examples and patterns

## Generation Guidelines

1. **Study the RPS Example**: `../text-game-engine/modules/rps/src/index.ts`
2. **Use ECS Patterns**: Follow Entity-Component-System architecture
3. **Generate Complete Games**: Include all necessary files for a working game
4. **Follow Conventions**: Match patterns from existing examples

## Output Structure

Generate each game in its own directory with this structure:
```
game-name/
├── src/
│   ├── index.ts        # Main game entry point
│   ├── components/     # Game-specific components
│   ├── systems/        # Game logic systems
│   └── actions/        # Player actions
├── config/
│   └── game.json       # Game configuration
└── README.md           # Game documentation
```
EOF

# Create a basic gitignore for generated content
cat > "$GENERATED_GAMES_DIR/.gitignore" << 'EOF'
# Generated game content - ignore everything except configuration
*
!.openswe/
!.gitignore
!README.md

# Allow specific games to be committed if needed
# !example-game/
EOF

# Create main README for generated-games
cat > "$GENERATED_GAMES_DIR/README.md" << 'EOF'
# Generated Games

This directory contains games generated by OpenSWE using the ChainCraft text-game-engine.

## OpenSWE Configuration

OpenSWE instructions are in the `.openswe/` directory:
- Game generation prompts
- Project context and guidelines
- Framework references

## Usage

1. Configure OpenSWE to operate on this directory
2. OpenSWE will read instructions from `.openswe/`
3. Generated games appear as subdirectories
4. Each game is self-contained and playable

## Generated Game Structure

```
game-name/
├── src/           # Game source code
├── config/        # Game configuration  
└── README.md      # Game documentation
```

## Framework Integration

Generated games use the ChainCraft text-game-engine:
- ECS architecture with entities, components, systems
- Pre-built components for common game mechanics
- Established patterns from example games
EOF

echo "✅ Generated-games directory setup complete!"
echo ""

# Copy OpenSWE environment configuration
echo "� Copying OpenSWE environment configuration..."
if [ -f "$WORKSPACE_ROOT/open-swe/apps/cli/.env" ]; then
    cp "$WORKSPACE_ROOT/open-swe/apps/cli/.env" "$GENERATED_GAMES_DIR/.env"
    echo "✅ Environment configuration copied to generated-games/"
else
    echo "⚠️  OpenSWE .env file not found - run setup-openswe.sh first"
fi
echo ""

echo "�📍 Directory structure created:"
echo "generated-games/"
echo "├── .openswe/              # OpenSWE instructions"
echo "├── .env                   # Environment configuration"
echo "├── .gitignore             # Git configuration"
echo "└── README.md              # Usage documentation"
echo ""
echo "🎯 OpenSWE can now operate on: $GENERATED_GAMES_DIR"
