/**
 * Superhero Showdown - Real production fixture with validation failures
 *
 * Game: 2-player narrative battle where AI generates a wrestling-announcer-style
 * story (400-450 chars) that determines a winner.
 * Spec clearly states: "No possibility of draws—there must always be a victor"
 *
 * Instructions were generated by Sonnet but never set isGameWinner for any player.
 * The coordinator must:
 * 1. Recognize this game requires a WINNER (spec says "exactly one winner")
 * 2. Recognize instructions need PATCHING (they exist but are missing isGameWinner ops)
 * 3. Target the game-ending transition for the fix
 * 4. Address both validation errors
 */

import type { CoordinatorInput } from '#chaincraft/ai/simulate/graphs/artifact-editor-graph/types.js';

// Real spec from production export (trimmed to key sections for coordinator reasoning)
export const SUPERHERO_SHOWDOWN_SPEC = `# Superhero Showdown - Game Specification

## Game Overview

Superhero Showdown is a 2-player narrative battle game where each player submits a custom superhero character description, and the game generates a concise, wrestling-announcer-style battle story (400-450 characters) that determines a winner.

**Player Count:** 2 players

## Character Submission Phase

**Submission Requirements:**
- Each player submits one character description for their superhero
- Submissions are free-form with no restrictions or requirements
- Any submission is accepted regardless of length, format, or content
- Players submit characters simultaneously (order does not matter)
- Players cannot see each other's submissions during this phase
- Game proceeds automatically to narrative generation once both submissions are received

## Narrative Generation

**Automatic Story Creation:**
- The game automatically generates a complete narrative battle story based on both character submissions
- Generation begins immediately and automatically when both characters are submitted
- Players have no input during story generation—it is fully automated
- Story incorporates specific details from both character descriptions to personalize the battle
- **The complete generated narrative must be between 400-450 characters in total length**

**Story Structure:**
The narrative follows a clear arc: Opening Introduction → Escalating Action → Climactic Moment → Definitive Conclusion

**Definitive Conclusion:**
- Clear narrative resolution where one character emerges victorious
- Victory emerges through story progression, not random chance
- Explicit winner announcement
- No possibility of draws—there must always be a victor

**Automatic Winner Declaration:**
- The narrative automatically concludes with a clear winner announcement
- Winner is declared within the narrative text itself
- Winner announcement is explicit and unambiguous
- No draws or ties are possible—every narrative must declare exactly one victor

## Victory Determination

**How Winners Are Decided:**
- Victory is determined solely by narrative outcome
- The story itself declares which character wins
- No mechanical rolls, stats, or player decisions during the battle affect the outcome
- Winner emerges through the logic and progression of the generated story
- The narrative must always conclude with a clear victor announcement

## Game End

**End Condition:**
- One player is declared the winner through narrative outcome
- The other player loses
- There are no draws—every game must have exactly one winner

**Display Format:**
- Header: [Player 1 Character Name] VS [Player 2 Character Name]
- Narrative: The 400-450 character battle story
- Footer: A winner is: [Winner's Character Name]`;

// Schema fields from export — matches real production schema
export const SUPERHERO_SHOWDOWN_SCHEMA_FIELDS = `game.currentPhase: string (tracks current game phase)
game.gameEnded: boolean (whether the game has ended)
game.publicMessage: string (public game state/instructions to all players)
game.winningPlayers: array of strings (player IDs who have won)
game.battleNarrative: string (store generated 400-450 character battle story)
game.narrativeGenerated: boolean (track whether battle narrative generation is complete)
players.*.illegalActionCount: number
players.*.privateMessage: string
players.*.actionsAllowed: boolean|null
players.*.actionRequired: boolean
players.*.isGameWinner: boolean (whether this player has won — must be explicitly set)
players.*.characterDescription: string (player's submitted superhero character description)`;

// Transitions matching the instructions' 4-transition phase model
// (from the failed extraction run — differs from the later successful export)
export const SUPERHERO_SHOWDOWN_TRANSITIONS = JSON.stringify({
  phases: ["init", "player_1_creating", "player_2_creating", "narrative_display", "finished"],
  transitions: [
    {
      id: "initialize_game",
      fromPhase: "init",
      toPhase: "player_1_creating",
      preconditions: [{
        id: "game_not_initialized",
        logic: { "or": [{ "==": [{ "var": "game.currentPhase" }, "init"] }, { "==": [{ "var": "game.currentPhase" }, null] }] },
        deterministic: true
      }]
    },
    {
      id: "player_1_submitted",
      fromPhase: "player_1_creating",
      toPhase: "player_2_creating",
      preconditions: [{
        id: "player1_done",
        logic: { "allPlayers": ["actionRequired", "==", false] },
        deterministic: true
      }]
    },
    {
      id: "player_2_submitted",
      fromPhase: "player_2_creating",
      toPhase: "narrative_display",
      preconditions: [{
        id: "player2_done",
        logic: { "allPlayers": ["actionRequired", "==", false] },
        deterministic: true
      }]
    },
    {
      id: "narrative_displayed",
      fromPhase: "narrative_display",
      toPhase: "finished",
      preconditions: [{
        id: "narrative_ready",
        logic: { "!=": [{ "var": "game.battleNarrative" }, ""] },
        deterministic: true
      }]
    }
  ]
}, null, 2);

// ─── Real generated instructions from the FAILED extraction run ───
// Generated by Sonnet — instructions exist but never set isGameWinner anywhere.
// This is the actual production output that triggered validation failures.

export const SUPERHERO_SHOWDOWN_TRANSITION_INSTRUCTIONS = {
  initialize_game: {
    id: "initialize_game",
    transitionName: "Initialize Game",
    mechanicsGuidance: null,
    rngConfig: null,
    stateDelta: [
      { op: "set", path: "game.currentPhase", value: "player_1_creating" },
      { op: "set", path: "game.gameEnded", value: false },
      { op: "setForAllPlayers", field: "illegalActionCount", value: 0 },
      { op: "setForAllPlayers", field: "actionRequired", value: false },
      { op: "set", path: "players.{{player1Id}}.actionRequired", value: true },
    ],
    messages: {
      public: { template: "Welcome to Superhero Showdown! Player 1 will create their superhero first." },
      private: [
        { to: "{{player1Id}}", template: "You're up first! Describe your superhero character in at least 10 characters (max 2000)." },
        { to: "{{player2Id}}", template: "Player 1 is creating their superhero. You'll get your turn next!" },
      ],
    },
  },
  player_1_submitted: {
    id: "player_1_submitted",
    transitionName: "Player 1 Submitted",
    mechanicsGuidance: null,
    rngConfig: null,
    stateDelta: [
      { op: "set", path: "game.currentPhase", value: "player_2_creating" },
      { op: "set", path: "players.{{player2Id}}.actionRequired", value: true },
    ],
    messages: {
      public: { template: "Player 1 has finished creating their superhero! Now it's Player 2's turn." },
      private: [
        { to: "{{player1Id}}", template: "Great! Now wait while Player 2 creates their superhero." },
        { to: "{{player2Id}}", template: "It's your turn! Describe your superhero character in at least 10 characters (max 2000)." },
      ],
    },
  },
  player_2_submitted: {
    id: "player_2_submitted",
    transitionName: "Generate Battle Narrative",
    mechanicsGuidance: {
      rules: [
        "Generate a complete battle narrative that is 3-5 paragraphs (approximately 300-600 words)",
        "Must depict a battle between both superheroes from start to finish",
        "Must incorporate all key details from both player descriptions",
        "Must include unexpected or ridiculous outcomes",
        "Must feature exaggerated, comedic tone throughout",
      ],
      computation: "Generate a creative, entertaining battle narrative stored in game.battleNarrative",
    },
    rngConfig: null,
    // NOTE: stateDelta sets battleNarrative but NEVER sets isGameWinner — this is the bug
    stateDelta: [
      { op: "set", path: "game.currentPhase", value: "narrative_display" },
      { op: "set", path: "game.battleNarrative", value: "{{generatedNarrative}}" },
    ],
    messages: {
      public: { template: "Both superheroes are ready! Generating the epic battle narrative..." },
    },
  },
  narrative_displayed: {
    id: "narrative_displayed",
    transitionName: "End Game",
    mechanicsGuidance: null,
    rngConfig: null,
    // NOTE: sets gameEnded but NEVER sets isGameWinner — validation failure
    stateDelta: [
      { op: "set", path: "game.currentPhase", value: "finished" },
      { op: "set", path: "game.gameEnded", value: true },
    ],
    messages: {
      public: {
        template: "🦸 SUPERHERO SHOWDOWN 🦸\n\n=== THE BATTLE ===\n{{game.battleNarrative}}\n\nThanks for playing Superhero Showdown!",
      },
    },
  },
};

export const SUPERHERO_SHOWDOWN_PLAYER_PHASE_INSTRUCTIONS = {
  player_1_creating: {
    phase: "player_1_creating",
    playerActions: [{
      id: "submit_superhero_description",
      actionName: "Submit Superhero Description",
      validation: {
        checks: [
          { id: "wrongPhase", logic: { "==": [{ "var": "game.currentPhase" }, "player_1_creating"] }, errorMessage: "Not in player 1 creation phase" },
          { id: "alreadySubmitted", logic: { "!": { "var": "players.{{playerId}}.superheroDescription" } }, errorMessage: "Already submitted" },
        ],
      },
      mechanicsGuidance: null,
      stateDelta: [
        { op: "set", path: "players.{{playerId}}.superheroDescription", value: "{{input.superheroDescription}}" },
        { op: "set", path: "players.{{playerId}}.actionRequired", value: false },
      ],
      messages: {
        private: [{ to: "{{playerId}}", template: "Your superhero has been created!" }],
        public: { template: "Player 1 has created their superhero! Waiting for Player 2..." },
      },
    }],
  },
  player_2_creating: {
    phase: "player_2_creating",
    playerActions: [{
      id: "submit_superhero_description",
      actionName: "Submit Superhero Description",
      validation: {
        checks: [
          { id: "wrongPhase", logic: { "==": [{ "var": "game.currentPhase" }, "player_2_creating"] }, errorMessage: "Not in player 2 creation phase" },
          { id: "alreadySubmitted", logic: { "!": { "var": "players.{{playerId}}.superheroDescription" } }, errorMessage: "Already submitted" },
        ],
      },
      mechanicsGuidance: null,
      stateDelta: [
        { op: "set", path: "players.{{playerId}}.superheroDescription", value: "{{input.superheroDescription}}" },
        { op: "set", path: "players.{{playerId}}.actionRequired", value: false },
      ],
      messages: {
        private: [{ to: "{{playerId}}", template: "Your superhero has been created!" }],
        public: { template: "Player 2 has created their superhero! Generating epic battle narrative..." },
      },
    }],
  },
};

export const SUPERHERO_SHOWDOWN_VALIDATION_ERRORS = [
  'No transition sets players.*.isGameWinner. At least one transition must mark winning players. Set isGameWinner=true for each winning player before or when the game ends. Runtime will automatically compute game.winningPlayers from these flags.',
  'No path to "finished" sets players.*.isGameWinner. If your game has winners, at least one ending path must set isGameWinner=true for winning players. If this is a draw-only game (no winners), you can ignore this warning.',
];

export const SUPERHERO_SHOWDOWN_INPUT: CoordinatorInput = {
  gameSpecification: SUPERHERO_SHOWDOWN_SPEC,
  validationErrors: SUPERHERO_SHOWDOWN_VALIDATION_ERRORS,
  schemaFields: SUPERHERO_SHOWDOWN_SCHEMA_FIELDS,
  stateTransitions: SUPERHERO_SHOWDOWN_TRANSITIONS,
  playerPhaseInstructions: JSON.stringify(SUPERHERO_SHOWDOWN_PLAYER_PHASE_INSTRUCTIONS),
  transitionInstructions: JSON.stringify(SUPERHERO_SHOWDOWN_TRANSITION_INSTRUCTIONS),
};
